env:
  es2021: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

rules:
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var:
    - error
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/indent':
    - error
    - 2
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/explicit-module-boundary-types':
    - error

overrides:
  - files:
    - src/common/enums/api/**/*
    rules:
      no-undef:
        - off
      '@typescript-eslint/no-var-requires':
        - off
